import Head from 'next/head'
import styles from '@/styles/Dashboard.module.css'
import { useState } from 'react'
import axios from 'axios';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from './components/sidebar';

export default function Dashboard() {
  const toastOptions = {
    position: "top-right",
    autoClose: 8000,
    pauseOnHover: true,
    draggable: true,
    theme: "dark",
  };

  const [isModalOpen, setIsModalOpen] = useState(false);

  function handleCreateVPSClick() {
    setIsModalOpen(true);
  }

  async function createvps() {
    try {
      const name = document.getElementById('vpsname').value;
      const os = document.getElementById('vpsos').value;
      const location = document.getElementById('vpslocation').value;

      console.log(name, os, location);
      const response = await axios.post(`http://192.9.162.98:8080/api/new`, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, X-Requested-With'
        },
        name: name,
        os: os,
        location: location,
      });
      console.log(response.data);
    } catch (error) {
      toast.error('An Error Occured', toastOptions);
      console.error(error);
    }
  };

  function Modal({ onClose, Component, pageProps }) {
    return (
      <>
        <Sidebar>
          <Component {...pageProps} />
        </Sidebar>
        <div className={styles.modal}>
          <div className={styles.modalContent}>
            <div className={styles.modalHeader}>
              <h2>Create VPS</h2>
              <button className={styles.close} onClick={onClose}>
                &times;
              </button>
            </div>
            <div className={styles.modalBody}>
              <form className={styles.form}>
                <label className={styles.label} htmlFor="name">Name:</label>
                <input
                  className={styles.input}
                  type="text"
                  id='vpsname'
                  minLength="3"
                  maxLength="20"
                />
                <label className={styles.label} htmlFor="os">Operating System:</label>
                <select
                  className={styles.input}
                  type="text"
                  id='vpsos'
                >
                  <option value="ubuntu-20.04">Ubuntu 20.04</option>
                  <option value="ubuntu-18.04">Ubuntu 18.04</option>
                  <option value="debian-10">Debian 10</option>
                  <option value="debian-9">Debian 9</option>
                  <option value="centos-8">CentOS 8</option>
                  <option value="centos-7">CentOS 7</option>
                </select>
                <label className={styles.label} htmlFor="location">Location:</label>
                <select
                  className={styles.input}
                  type="text"
                  id='vpslocation'
                >
                  <option value="Sydney NSW">Sydney NSW</option>
                  <option value="New York, NY">New York, NY</option>
                  <option value="London, UK">London, UK</option>
                </select>
              </form>
              <button onClick={createvps} type="submit">Create</button>
            </div>
          </div>
        </div>
      </>
    );
  }



  const servers = [
    { name: 'My cool server', os: 'ubuntu-20.04', location: 'Sydney NSW', status: 'online' },
    { name: 'Another server', os: 'debian-10', location: 'New York, NY', status: 'offline' },
    { name: 'Yet another server', os: 'centos-8', location: 'London, UK', status: 'online' },
  ];

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h2 className={styles.h2}>Virtural Servers, Manage Servers, Manage Plan <button id='createvps' className={styles.btn} onClick={handleCreateVPSClick}>Create VPS</button>{isModalOpen && <Modal onClose={() => setIsModalOpen(false)} />}</h2>
          <table className={styles.table}>
            <thead className={styles.thead}>
              <tr className={styles.tr}>
                <th className={styles.th}>ID</th>
                <th className={styles.th}>Server</th>
                <th className={styles.th}>OS</th>
                <th className={styles.th}>Location</th>
                <th className={styles.th}>Status</th>
              </tr>
            </thead>
            <tbody className={styles.tbody}>
              {servers.map((server, key) => (
                <tr key={server.name} className={styles.tr}>
                  <td className={styles.td}>{key + 1}</td>
                  <td className={styles.td}>{server.name}</td>
                  <td className={styles.td}>{server.os}</td>
                  <td className={styles.td}>{server.location}</td>
                  <td className={styles.td}>{server.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
      <ToastContainer />
    </>
  )
}
